name: "Content issue"
description: Report a problem with content on WAI website.
body:
  - type: input
    id: wai-url
    attributes:
      label: Resource URL
      description: The link to the page this issue is about or, if it's about multiple pages, an example or most important page.
    validations:
      required: true
  - type: input
    id: wai-id
    attributes:
      label: Resource shortname
      description: The shortname of the resource, as displayed in the "Help improve this page" box at the bottom of the resource.
  - type: textarea
    id: description
    attributes:
      label: Add a description