name: Pre-validate before deploy

on:
  workflow_dispatch
  
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update Externals
      run: |
        git submodule update --init --remote
    - name: Build and test with Jekyll
      run: |
        bundle exec jekyll build --profile --trace --config "_config.yml,_config_prod.yml" --profile
    - name: Generate list of resources
      run: |
        find ./_site -type f | sed 's,^\.\/_site,,' | sort > ./_site/manifest.txt
    - name: Check list of files
      run: |
        cat ./_site/manifest.txt
    - name: Check number of files
      run: |
        tree -al ./_site/ | tail -1
