name: Check before deploy

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
    - name: Install Netlify
      run: npm install netlify-cli@17 -g
    - name: Update Externals
      run: |
        git submodule update --init --remote
    - name: Build and test with Jekyll
      run: |
        bundle exec jekyll build --profile --trace --config "_config.yml,_config_prod.yml" --profile
    - name: Generate list of resources
      run: |
        find ./_site -type f | sed 's,^\.\/_site,,' | sort > ./_site/manifest.txt
    - name: Check number of files
      run: |
        tree -al ./_site/ | tail -1
        find ./_site -type f | cut -d/ -f2 | sort | uniq -c
    - name: Check list of files
      run: |
        cat ./_site/manifest.txt
    - name: Install dependencies
      run: |
        npm install
    - name: Generate Netlify preview
      id: netlify_deploy
      run: |
        netlify deploy \
          --dir _site \
          --functions _functions \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_API_TOKEN }}
